import { existsSync } from 'node:fs'
import { appendFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import type { ChronicleEntry } from '../../shared/types'

const WORLD_MATERIAL_PATH = resolve(process.cwd(), 'world-material.md')

const HEADER = `# World Material — Construction Guild Settlement

Generated by Backlog Saga. Every entry below was built by the Construction
Guild in response to a real completed TODO. Entries are append-only, oldest
first — read top to bottom for the settlement's growth.

An Oath bot may reference any building here by name when improvising a
session set in or near this settlement.
`

export async function appendWorldMaterial(entry: ChronicleEntry) {
  if (!existsSync(WORLD_MATERIAL_PATH)) {
    await writeFile(WORLD_MATERIAL_PATH, HEADER, 'utf-8')
  }
  const block = `
## Building No. ${entry.number} — the ${entry.buildingName}

- **Built:** ${entry.builtAt.slice(0, 10)}
- **Material:** ${entry.material}
- **Source task:** ${entry.sourceTask}

${entry.dispatch}
`
  await appendFile(WORLD_MATERIAL_PATH, block, 'utf-8')
}
