import { existsSync } from 'node:fs'
import { appendFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import type { ChronicleEntry } from '../../shared/types'
import { getFaction } from '../../shared/factions'

const WORLD_MATERIAL_PATH = resolve(process.cwd(), 'world-material.md')

const HEADER = `# World Material — Backlog Saga Settlement

Generated by Backlog Saga. Every entry below was produced by one of the
settlement's guild factions in response to a real completed TODO. Entries
are append-only, oldest first — read top to bottom for the settlement's
growth.

An Oath bot may reference any entry here by name when improvising a session
set in or near this settlement.
`

export async function appendWorldMaterial(entry: ChronicleEntry) {
  if (!existsSync(WORLD_MATERIAL_PATH)) {
    await writeFile(WORLD_MATERIAL_PATH, HEADER, 'utf-8')
  }
  const faction = getFaction(entry.category)
  const block = `
## Entry No. ${entry.number} — ${entry.resultName}

*${entry.subtype} (${faction.noun}), ${faction.doneVerb.toLowerCase()} by ${faction.factionName}.*

- **Built:** ${entry.builtAt.slice(0, 10)}
- **${faction.detailLabel}:** ${entry.resultDetail}
- **Source task:** ${entry.sourceTask}

${entry.dispatch}
`
  await appendFile(WORLD_MATERIAL_PATH, block, 'utf-8')
}
